insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (1, 'Buell', 'Brazil', null, 'Porangatu', '76550-000');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (2, 'Laurel', 'Philippines', null, 'Mahaplag', '6512');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (3, 'Crescent Oaks', 'Poland', null, 'Rachanie', '22-640');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (4, 'Spenser', 'France', 'Rhône-Alpes', 'Aime', '73216 CEDEX');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (5, 'Coleman', 'United States', 'Ohio', 'Columbus', '43220');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (6, 'Ramsey', 'Sweden', 'Östergötland', 'Norrköping', '602 09');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (7, 'Porter', 'Madagascar', null, 'Ambanja', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (8, 'Canary', 'Sri Lanka', null, 'Anuradhapura', '50000');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (9, 'Carioca', 'Madagascar', null, 'Soanindrariny', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (10, 'Nancy', 'Mongolia', null, 'Mandal', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (11, 'Commercial', 'France', 'Nord-Pas-de-Calais', 'Lille', '59895 CEDEX 9');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (12, 'Pine View', 'Albania', null, 'Mamurras', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (13, 'Armistice', 'South Korea', null, 'Hayang', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (14, 'Continental', 'Sweden', 'Västra Götaland', 'Mölndal', '431 87');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (15, 'Dovetail', 'Indonesia', null, 'Barapas', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (16, 'Monterey', 'China', null, 'Xiasha', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (17, 'Mitchell', 'Hong Kong', null, 'Sok Kwu Wan', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (18, 'Jenifer', 'Guatemala', null, 'San Marcos', '12001');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (19, 'Erie', 'Panama', null, 'Guarumal', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (20, 'Sugar', 'Serbia', null, 'Leskovac', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (21, 'Bonner', 'France', 'Bretagne', 'Rennes', '35087 CEDEX');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (22, 'Lakewood Gardens', 'Mali', null, 'Kinmparana', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (23, 'Waubesa', 'East Timor', null, 'Venilale', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (24, 'Sutteridge', 'Portugal', 'Lisboa', 'Olival Basto', '2620-005');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (25, 'Stoughton', 'Indonesia', null, 'Bokor', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (26, 'Saint Paul', 'China', null, 'Zhangbang', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (27, 'East', 'Indonesia', null, 'Bojongsari', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (28, 'Sheridan', 'China', null, 'Huanggexi', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (29, 'Forster', 'Netherlands', 'Provincie Zuid-Holland', 'Leiden', '2304');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (30, 'New Castle', 'Albania', null, 'Guri i Zi', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (31, 'Kings', 'Indonesia', null, 'Brondong', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (32, 'David', 'Indonesia', null, 'Tlutup', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (33, 'John Wall', 'Philippines', null, 'Basing', '2417');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (34, 'Susan', 'Portugal', 'Vila Real', 'Granja', '5070-085');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (35, 'Garrison', 'Germany', 'Sachsen', 'Leipzig', '04317');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (36, 'Bonner', 'Russia', null, 'Vyksa', '607069');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (37, 'Independence', 'Indonesia', null, 'Krajan Tengah', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (38, '2nd', 'United States', 'Texas', 'Denton', '76205');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (39, 'Fair Oaks', 'Czech Republic', null, 'Sviadnov', '739 25');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (40, 'Magdeline', 'China', null, 'Sanli', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (41, 'Coleman', 'Brazil', null, 'Simões Filho', '43700-000');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (42, 'Hanover', 'United States', 'Massachusetts', 'Boston', '02216');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (43, 'Delaware', 'Indonesia', null, 'Sumberkenanga', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (44, 'Fair Oaks', 'Greece', null, 'Neochóri', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (45, 'Crescent Oaks', 'Brazil', null, 'Sinop', '78550-000');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (46, 'Oakridge', 'Indonesia', null, 'Sungaimaja', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (47, 'Pond', 'Czech Republic', null, 'Seč', '798 45');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (48, 'Thackeray', 'China', null, 'Tiecun', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (49, 'Arrowood', 'Poland', null, 'Lutowiska', '38-713');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (50, 'Debs', 'Poland', null, 'Księżpol', '23-415');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (51, 'Lukken', 'Nicaragua', null, 'Santo Domingo', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (52, 'Eliot', 'Philippines', null, 'Aborlan', '5302');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (53, 'Parkside', 'Portugal', 'Leiria', 'Covão da Carvalha', '2485-203');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (54, 'Oak Valley', 'Zambia', null, 'Mansa', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (55, 'Lyons', 'Canada', 'Québec', 'Kingsey Falls', 'T8H');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (56, 'Browning', 'China', null, 'Huangtan', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (57, 'Southridge', 'Russia', null, 'Mogocha', '673732');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (58, 'Redwing', 'Bangladesh', null, 'Rājshāhi', '6100');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (59, 'Messerschmidt', 'China', null, 'Shangyi', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (60, 'Continental', 'Sweden', 'Stockholm', 'Stockholm', '117 97');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (61, 'Express', 'Indonesia', null, 'Munturkaju', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (62, 'Stang', 'Thailand', null, 'Nong Phok', '45210');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (63, 'Northwestern', 'Indonesia', null, 'Mojomulyokrajan', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (64, 'Weeping Birch', 'Ukraine', null, 'Kostryzhivka', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (65, 'Spenser', 'Madagascar', null, 'Andramasina', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (66, 'Longview', 'China', null, 'Huangcai', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (67, 'Bluestem', 'Ecuador', null, 'Cuenca', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (68, 'Old Shore', 'Ethiopia', null, 'Mekele', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (69, 'Anthes', 'France', 'Pays de la Loire', 'Ancenis', '44159 CEDEX');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (70, 'Nova', 'Japan', null, 'Hitachi', '319-1417');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (71, 'Mccormick', 'Russia', null, 'Groznyy', '385798');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (72, 'Lukken', 'China', null, 'Xushuguan', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (73, 'Menomonie', 'Russia', null, 'Khorinsk', '671410');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (74, 'Bunker Hill', 'Sweden', 'Skåne', 'Bjuv', '267 35');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (75, 'Upham', 'Ukraine', null, 'Kyrylivka', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (76, 'Service', 'Ireland', null, 'Kingscourt', 'F45');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (77, 'Sauthoff', 'Serbia', null, 'Kulpin', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (78, 'Myrtle', 'China', null, 'Cengjia', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (79, 'Village Green', 'Indonesia', null, 'Kampunganyar', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (80, 'Maple Wood', 'Nigeria', null, 'Bama', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (81, 'Burrows', 'France', 'Champagne-Ardenne', 'Langres', '52204 CEDEX');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (82, 'Summit', 'China', null, 'Xuji', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (83, 'Reinke', 'Portugal', 'Lisboa', 'Santa Iria de Azóia', '2690-147');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (84, 'Hoffman', 'Nigeria', null, 'Funtua', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (85, 'Warbler', 'Brazil', null, 'Beberibe', '62840-000');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (86, 'Cherokee', 'Russia', null, 'Ventsy', '352177');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (87, '7th', 'Indonesia', null, 'Sekartaji', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (88, 'Meadow Valley', 'Ukraine', null, 'Rozsypne', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (89, 'Twin Pines', 'Russia', null, 'Mgachi', '634003');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (90, 'Shopko', 'Niger', null, 'Tibiri', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (91, 'Crescent Oaks', 'Croatia', null, 'Zdenci', '33513');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (92, 'Hazelcrest', 'Ukraine', null, 'Kodyma', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (93, 'Arkansas', 'China', null, 'Xihuaiba', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (94, 'Northport', 'Japan', null, 'Tsushima', '979-1757');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (95, 'Oriole', 'Poland', null, 'Praga Północ', '05-094');
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (96, 'Fallview', 'Bosnia and Herzegovina', null, 'Rumboci', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (97, '8th', 'China', null, 'Junliangcheng', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (98, 'Jana', 'Indonesia', null, 'Waitenepang', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (99, 'Holy Cross', 'Indonesia', null, 'Pandanwangi', null);
insert into LOCATION_MOCK_DATA (id, name, country, state, city, zipcode) values (100, 'Miller', 'Croatia', null, 'Zmijavci', '21266');
