insert into locations (id, name, country, state, city, zipcode) values (1, 'Esker', 'Mexico', 'Guanajuato', 'Guadalupe', '38204');
insert into locations (id, name, country, state, city, zipcode) values (2, 'Mccormick', 'China', null, 'Zhuoshui', null);
insert into locations (id, name, country, state, city, zipcode) values (3, 'Northwestern', 'Russia', null, 'Lyalichi', '692658');
insert into locations (id, name, country, state, city, zipcode) values (4, 'Banding', 'Egypt', null, 'Maţāy', null);
insert into locations (id, name, country, state, city, zipcode) values (5, 'Dovetail', 'China', null, 'Tiemen', null);
insert into locations (id, name, country, state, city, zipcode) values (6, 'Saint Paul', 'Japan', null, 'Ōkawara', '989-1323');
insert into locations (id, name, country, state, city, zipcode) values (7, 'Blaine', 'Portugal', 'Évora', 'Monte do Outeiro', '7005-719');
insert into locations (id, name, country, state, city, zipcode) values (8, 'Lotheville', 'Cuba', null, 'Minas de Matahambre', null);
insert into locations (id, name, country, state, city, zipcode) values (9, 'Carioca', 'Japan', null, 'Kan’onjichō', '769-1613');
insert into locations (id, name, country, state, city, zipcode) values (10, 'Pearson', 'Russia', null, 'Shumerlya', '429127');
insert into locations (id, name, country, state, city, zipcode) values (11, 'Express', 'China', null, 'Songjianghe', null);
insert into locations (id, name, country, state, city, zipcode) values (12, 'Hooker', 'China', null, 'Canggou', null);
insert into locations (id, name, country, state, city, zipcode) values (13, 'Summer Ridge', 'China', null, 'Lishu', null);
insert into locations (id, name, country, state, city, zipcode) values (14, 'David', 'Malta', null, 'Senglea', 'ZTN');
insert into locations (id, name, country, state, city, zipcode) values (15, 'Lighthouse Bay', 'China', null, 'Jishan', null);
insert into locations (id, name, country, state, city, zipcode) values (16, 'Hermina', 'Poland', null, 'Świętochłowice', '41-608');
insert into locations (id, name, country, state, city, zipcode) values (17, 'Aberg', 'South Africa', null, 'Cala', '5455');
insert into locations (id, name, country, state, city, zipcode) values (18, 'Badeau', 'Haiti', null, 'Petite Anse', null);
insert into locations (id, name, country, state, city, zipcode) values (19, 'Troy', 'Luxembourg', null, 'Strassen', 'L-8069');
insert into locations (id, name, country, state, city, zipcode) values (20, 'Starling', 'Poland', null, 'Stare Juchy', '19-330');
insert into locations (id, name, country, state, city, zipcode) values (21, 'Marquette', 'Colombia', null, 'Acacías', '507009');
insert into locations (id, name, country, state, city, zipcode) values (22, 'Almo', 'Russia', null, 'Bastan', '658972');
insert into locations (id, name, country, state, city, zipcode) values (23, 'Little Fleur', 'China', null, 'Huanghuatan', null);
insert into locations (id, name, country, state, city, zipcode) values (24, 'Ramsey', 'Croatia', null, 'Ernestinovo', '31215');
insert into locations (id, name, country, state, city, zipcode) values (25, 'Buena Vista', 'Australia', 'New South Wales', 'Sydney', '1191');
insert into locations (id, name, country, state, city, zipcode) values (26, 'Daystar', 'Portugal', 'Porto', 'Finzes', '4785-228');
insert into locations (id, name, country, state, city, zipcode) values (27, 'Arizona', 'Colombia', null, 'Popayán', '190018');
insert into locations (id, name, country, state, city, zipcode) values (28, 'Dakota', 'Japan', null, 'Takefu', '919-0201');
insert into locations (id, name, country, state, city, zipcode) values (29, 'Towne', 'Indonesia', null, 'Ciparay', null);
insert into locations (id, name, country, state, city, zipcode) values (30, 'Susan', 'Luxembourg', null, 'Bettendorf', 'L-9359');
insert into locations (id, name, country, state, city, zipcode) values (31, 'Basil', 'Mexico', 'Chiapas', 'Alvaro Obregon', '29913');
insert into locations (id, name, country, state, city, zipcode) values (32, 'South', 'Poland', null, 'Warlubie', '86-160');
insert into locations (id, name, country, state, city, zipcode) values (33, '6th', 'Indonesia', null, 'Ciputih', null);
insert into locations (id, name, country, state, city, zipcode) values (34, 'Duke', 'China', null, 'Dongfeng', null);
insert into locations (id, name, country, state, city, zipcode) values (35, 'Fairview', 'New Zealand', null, 'Coromandel', '3543');
insert into locations (id, name, country, state, city, zipcode) values (36, 'Duke', 'Vietnam', null, 'Tánh Linh', null);
insert into locations (id, name, country, state, city, zipcode) values (37, 'Arizona', 'Indonesia', null, 'Banjar Kertasari', null);
insert into locations (id, name, country, state, city, zipcode) values (38, 'Oak', 'Liberia', null, 'Gbarnga', null);
insert into locations (id, name, country, state, city, zipcode) values (39, 'Drewry', 'Philippines', null, 'Balogo', '6542');
insert into locations (id, name, country, state, city, zipcode) values (40, 'Vahlen', 'Portugal', 'Porto', 'Campos', '4620-031');
insert into locations (id, name, country, state, city, zipcode) values (41, 'Crownhardt', 'Japan', null, 'Ueki', '938-0014');
insert into locations (id, name, country, state, city, zipcode) values (42, 'Sunbrook', 'Philippines', null, 'Moncada', '2334');
insert into locations (id, name, country, state, city, zipcode) values (43, 'Doe Crossing', 'China', null, 'Wushan', null);
insert into locations (id, name, country, state, city, zipcode) values (44, 'Karstens', 'Guatemala', null, 'San Antonio Ilotenango', '14008');
insert into locations (id, name, country, state, city, zipcode) values (45, 'Macpherson', 'Jamaica', null, 'Saint Ann’s Bay', null);
insert into locations (id, name, country, state, city, zipcode) values (46, 'Acker', 'South Africa', null, 'Graksop', '1274');
insert into locations (id, name, country, state, city, zipcode) values (47, 'Ruskin', 'Indonesia', null, 'Krajan Dua Padomasan', null);
insert into locations (id, name, country, state, city, zipcode) values (48, 'Barnett', 'Indonesia', null, 'Pohonsirih', null);
insert into locations (id, name, country, state, city, zipcode) values (49, 'Old Shore', 'Argentina', null, 'San Carlos de Bariloche', '8400');
insert into locations (id, name, country, state, city, zipcode) values (50, 'Barnett', 'China', null, 'Chengfeng', null);
insert into locations (id, name, country, state, city, zipcode) values (51, 'Schiller', 'Peru', null, 'Uticyacu', null);
insert into locations (id, name, country, state, city, zipcode) values (52, 'Oak', 'Namibia', null, 'Eenhana', null);
insert into locations (id, name, country, state, city, zipcode) values (53, 'John Wall', 'Portugal', 'Aveiro', 'Sarrazola', '3800-596');
insert into locations (id, name, country, state, city, zipcode) values (54, 'Bartillon', 'China', null, 'Samdo', null);
insert into locations (id, name, country, state, city, zipcode) values (55, 'Leroy', 'Sweden', 'Västerbotten', 'Dorotea', '917 32');
insert into locations (id, name, country, state, city, zipcode) values (56, 'Truax', 'Peru', null, 'Celendín', null);
insert into locations (id, name, country, state, city, zipcode) values (57, 'Browning', 'Indonesia', null, 'Pasatan', null);
insert into locations (id, name, country, state, city, zipcode) values (58, 'Autumn Leaf', 'Colombia', null, 'Hobo', '413067');
insert into locations (id, name, country, state, city, zipcode) values (59, 'Dwight', 'China', null, 'Dailing', null);
insert into locations (id, name, country, state, city, zipcode) values (60, 'Nevada', 'Indonesia', null, 'Gunungmenang', null);
insert into locations (id, name, country, state, city, zipcode) values (61, 'Oak Valley', 'Niger', null, 'Mirriah', null);
insert into locations (id, name, country, state, city, zipcode) values (62, 'Carpenter', 'China', null, 'Bazi', null);
insert into locations (id, name, country, state, city, zipcode) values (63, 'Northview', 'Uganda', null, 'Ntungamo', null);
insert into locations (id, name, country, state, city, zipcode) values (64, 'Spaight', 'Poland', null, 'Łodygowice', '34-325');
insert into locations (id, name, country, state, city, zipcode) values (65, 'Ronald Regan', 'China', null, 'Hengzhou', null);
insert into locations (id, name, country, state, city, zipcode) values (66, 'Logan', 'Cuba', null, 'Sagua la Grande', null);
insert into locations (id, name, country, state, city, zipcode) values (67, 'Talmadge', 'France', 'Provence-Alpes-Côte d''Azur', 'Avignon', '84007 CEDEX 1');
insert into locations (id, name, country, state, city, zipcode) values (68, 'Mcbride', 'Palestinian Territory', null, 'Tarqūmyā', null);
insert into locations (id, name, country, state, city, zipcode) values (69, 'Michigan', 'Venezuela', null, 'San Francisco', null);
insert into locations (id, name, country, state, city, zipcode) values (70, 'Loftsgordon', 'Sweden', 'Östergötland', 'Linköping', '587 24');
insert into locations (id, name, country, state, city, zipcode) values (71, 'Morning', 'Malaysia', 'Kuala Lumpur', 'Kuala Lumpur', '50515');
insert into locations (id, name, country, state, city, zipcode) values (72, 'Helena', 'Ivory Coast', null, 'Sinfra', null);
insert into locations (id, name, country, state, city, zipcode) values (73, 'Reinke', 'Portugal', 'Leiria', 'Moita da Roda', '2425-839');
insert into locations (id, name, country, state, city, zipcode) values (74, 'Fulton', 'Brazil', null, 'Sertânia', '56600-000');
insert into locations (id, name, country, state, city, zipcode) values (75, 'Summit', 'Philippines', null, 'Paoay', '2902');
insert into locations (id, name, country, state, city, zipcode) values (76, 'Cambridge', 'Ukraine', null, 'Storozhynets’', null);
insert into locations (id, name, country, state, city, zipcode) values (77, 'Crownhardt', 'China', null, 'Jiangkou', null);
insert into locations (id, name, country, state, city, zipcode) values (78, 'Michigan', 'Russia', null, 'Saransk', '430910');
insert into locations (id, name, country, state, city, zipcode) values (79, 'Rutledge', 'China', null, 'Gensi', null);
insert into locations (id, name, country, state, city, zipcode) values (80, 'Graceland', 'Philippines', null, 'Bantogon', '5322');
insert into locations (id, name, country, state, city, zipcode) values (81, 'Center', 'Thailand', null, 'Phetchabun', '45110');
insert into locations (id, name, country, state, city, zipcode) values (82, 'Straubel', 'Brazil', null, 'Goiana', '55900-000');
insert into locations (id, name, country, state, city, zipcode) values (83, 'Susan', 'Indonesia', null, 'Pasirhaur', null);
insert into locations (id, name, country, state, city, zipcode) values (84, 'Kennedy', 'Angola', null, 'Nzeto', null);
insert into locations (id, name, country, state, city, zipcode) values (85, 'Surrey', 'Slovenia', null, 'Portorož', '6333');
insert into locations (id, name, country, state, city, zipcode) values (86, 'Melody', 'Thailand', null, 'Phatthana Nikhom', '53230');
insert into locations (id, name, country, state, city, zipcode) values (87, 'Bultman', 'Indonesia', null, 'Kalapadua', null);
insert into locations (id, name, country, state, city, zipcode) values (88, 'Corscot', 'Russia', null, 'Chistopol’', '422986');
insert into locations (id, name, country, state, city, zipcode) values (89, 'Green Ridge', 'Japan', null, 'Ōarai', '311-1500');
insert into locations (id, name, country, state, city, zipcode) values (90, 'Westport', 'Brazil', null, 'Limoeiro de Anadia', '57260-000');
insert into locations (id, name, country, state, city, zipcode) values (91, 'Fisk', 'South Africa', null, 'Potchefstroom', '2538');
insert into locations (id, name, country, state, city, zipcode) values (92, 'Grasskamp', 'Indonesia', null, 'Kerep Wetan', null);
insert into locations (id, name, country, state, city, zipcode) values (93, 'Roxbury', 'China', null, 'Jibu Hulangtu', null);
insert into locations (id, name, country, state, city, zipcode) values (94, 'Butterfield', 'Uzbekistan', null, 'G‘azalkent', null);
insert into locations (id, name, country, state, city, zipcode) values (95, 'Riverside', 'South Africa', null, 'Heidelberg', '1444');
insert into locations (id, name, country, state, city, zipcode) values (96, 'Morningstar', 'Nepal', null, 'Birendranagar', null);
insert into locations (id, name, country, state, city, zipcode) values (97, 'Raven', 'Mongolia', null, 'Jargalant', null);
insert into locations (id, name, country, state, city, zipcode) values (98, 'Transport', 'Yemen', null, 'Al Munīrah', null);
insert into locations (id, name, country, state, city, zipcode) values (99, 'Onsgard', 'Indonesia', null, 'Haruman', null);
insert into locations (id, name, country, state, city, zipcode) values (100, 'Rockefeller', 'China', null, 'Jianqiao', null);
